### ISSUE TITLE
HTTP 500 on fo'mo

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#748] opened 2020-03-14 20:27 UTC
Incident on Mar 14 at 4pm ET:
1. High response times
2. Failed requests
3. HTTP 500 errors

Restarting the dynos seemed to fix it. But saw this error for the 500 response on Scalyr:
```
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435141+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435141+00:00 host app web.1 -     return self.render(context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435142+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435142+00:00 host app web.1 -     result = block.nodelist.render(context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435143+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 937, in render
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435143+00:00 host app web.1 -     bit = node.render_annotated(context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435143+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435144+00:00 host app web.1 -     return self.render(context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435144+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435145+00:00 host app web.1 -     nodelist.append(node.render_annotated(context))
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435145+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435145+00:00 host app web.1 -     return self.render(context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435146+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435146+00:00 host app web.1 -     return nodelist.render(context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435146+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 937, in render
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435147+00:00 host app web.1 -     bit = node.render_annotated(context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435147+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435148+00:00 host app web.1 -     return self.render(context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435148+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/core/templatetags/wagtailcore_tags.py", line 125, in render
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435149+00:00 host app web.1 -     return value.render_as_block(context=new_context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435149+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/core/blocks/base.py", line 430, in render_as_block
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435150+00:00 host app web.1 -     return self.block.render(self.value, context=context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435150+00:00 host app web.1 -   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/core/blocks/base.py", line 244, in render
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435151+00:00 host app web.1 -     new_context = self.get_context(value, parent_context=dict(context))
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435151+00:00 host app web.1 -   File "/app/network-api/networkapi/wagtailpages/pagemodels/customblocks/recent_blog_entries.py", line 78, in get_context
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435151+00:00 host app web.1 -     entries = blogpage.get_entries(context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435153+00:00 host app web.1 -   File "/app/network-api/networkapi/wagtailpages/pagemodels/index.py", line 86, in get_entries
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435154+00:00 host app web.1 -     entries = self.filter_entries(entries, context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435154+00:00 host app web.1 -   File "/app/network-api/networkapi/wagtailpages/pagemodels/blog_index.py", line 28, in filter_entries
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435154+00:00 host app web.1 -     entries = self.filter_entries_for_category(entries, context)
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435155+00:00 host app web.1 -   File "/app/network-api/networkapi/wagtailpages/pagemodels/blog_index.py", line 51, in filter_entries_for_category
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435155+00:00 host app web.1 -     entry in entries.specific()
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435156+00:00 host app web.1 -   File "/app/network-api/networkapi/wagtailpages/pagemodels/blog_index.py", line 55, in <listcomp>
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435156+00:00 host app web.1 -     category in entry.category.all()
 16:13:36.619 foundation.mozilla.org logplex <190>1 2020-03-14T20:13:36.435156+00:00 host app web.1 - TypeError: argument of type 'QuerySet' is not iterable
```

**Comment by gideonthomas** [comment] 2020-03-14 20:28
cc @Pomax and @cadecairos

**Comment by Pomax** [comment] 2020-03-14 20:50
@gideonthomas the log looks cut off, which URL is this on?

**Comment by Pomax** [comment] 2020-03-14 21:03
Looing at https://foundation.mozilla.org/en/blog/, this appears to be related to the fact that our MozBeat posts don't have a category, which makes it mighty hard for code that expects a category to actually do much =)

@kristinashu @caltrider should we have a dedicated category for these kind of posts? Also, is there a category that we should use for blog posts that aren't explicitly marked as being in a specific category?

(in addition to fixing the code that assumes a category exists, of course)

**Comment by Pomax** [comment] 2020-03-14 21:07
I thought this might be because mozbeat blog posts don't have any categories, but https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/pagemodels/blog_index.py#L49-L55 already checks for the presence of categories.... it might still be part of the problem here, but without a URL on which we know these 500 occur on, it'll be hard to debug.

**Comment by patjouk** [comment] 2020-03-16 07:44
It seems to be coming from:
` 15:04:49.547 foundation.mozilla.org logplex <190>1 2020-03-13T14:04:49.182551+00:00 host app web.1 - Internal Server Error: /en/internet-health-report/blog/`
`20:51:55.409 foundation.mozilla.org logplex <190>1 2020-03-14T19:51:54.448521+00:00 host app web.1 - Internal Server Error: /en/blog/category/advocacy/`
` 21:00:14.696 foundation.mozilla.org logplex <190>1 2020-03-14T20:00:14.424875+00:00 host app web.1 - Internal Server Error: /en/blog/category/mozilla-festival/`
` 21:00:28.719 foundation.mozilla.org logplex <190>1 2020-03-14T20:00:28.400412+00:00 host app web.1 - Internal Server Error: /en/blog/category/fellowships-awards/`

**Comment by Pomax** [comment] 2020-03-16 14:33
I've been entirely unable to reproduce this locally, and the error seems to come from code that already got fixed, so I wonder if this was a case of an old dyno sticking around, rather than updating along with everything else.

**Comment by cadecairos** [comment] 2020-03-16 15:30
I'm looking closely at the logs around the time this started, and I'm wondering if this has more to do with unhealthy gunicorn threads after a dyno reboot. I'm going to open a PR with some recommendations from Heroku around configuring gunicorn.

**Comment by cadecairos** [comment] 2020-03-16 19:30
opened https://github.com/mozilla/foundation.mozilla.org/pull/4354

**Comment by cadecairos** [comment] 2020-04-01 14:13
This appears to be fixed, lets reopen if we see the problem again.

**Closed by cadecairos** 2020-04-01 14:13 UTC
Labels: devops
