### ISSUE TITLE
Prevent Pulse staging from being indexed

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#757] opened 2020-05-29 03:31 UTC
👋

I probably could have filed this in the Pulse repo, but I'd bet it ends up on your plates anyway: I was doing a "let's make sure nothing weird is showing up" vanity Google search for myself and noticed on page 2:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1682681/83217964-f4798080-a13a-11ea-942e-06bd348b0478.png">

**Comment by Pomax** [comment] 2021-04-26 21:29
This requires setting the `X-Robots-Tag` header to `noindex`, which should be fairly straight-forward in express.

**Comment by jencohoon** [comment] 2023-06-13 22:43
Marking this as closed - Can't reproduce this. 
Also Express js is not installed in: https://github.com/mozilla/network-pulse?search=1 or in https://github.com/mozilla/network-pulse-api?search=1 (search for express - there would be a configuration file present) 

Also, I can't find a sitemap.xml for mozillapulse.org/sitemap.xml so not sure how the mozillapulse site is indexed in the first place ... Did someone upload a sitemap.xml into Google Search Console??

**Closed by jencohoon** 2023-06-13 22:43 UTC
Labels: engineering

**Comment by alanmoo** [comment] 2023-06-14 00:41
Sorry, I should have been more clear in the original issue: the problem here was that staging is being indexed. I assume it should have some sort of noindex directive at a domain level, possibly outside the codebase. (I don't know if this is still an issue though)
