### ISSUE TITLE
Deploying Facebook Survey tool on Heroku

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/mofo-devops#589] opened 2018-04-25 16:47 UTC
### Details
We need to move a [tool](https://mozillafoundation.shinyapps.io/facebook/) that visualizes data for the recent Facebook survey from shinyapps.io, which we used for staging, to Heroku. The tool is built in R using the Shiny framework, its repo can be found [here](https://github.com/vojtechsedlak/shinysurvey). There is a [R buildpack](https://github.com/virtualstaticvoid/heroku-buildpack-r/tree/heroku-16) for Heroku, which we should hopefully be able to use.

There are no specific requirements for URL, so whatever is easiest. The tool has no trackers and doesn't collect any data, it just visualizes the survey data, which is included in the repo.

**Comment by cadecairos** [comment] 2018-04-25 16:53
I've forked the repo the the Mozilla org: https://github.com/mozilla/shinysurvey - we'll deploy this to Heroku.

I'm adding a `run.R` file so that the Heroku R Buildpack will pick it up and boot up the Shiny app.

I'm about to test it all out, will report back in a couple minutes!

**Comment by cadecairos** [comment] 2018-04-25 16:56
update: it builds and tries to start up. but has an error. debugging that now.

**Comment by vojtechsedlak** [comment] 2018-04-25 17:07
there are some package dependencies in the main server.R file, which may need to be installed as part of the build. Not sure whether that's the issue, but wanted to flag.

**Comment by cadecairos** [comment] 2018-04-25 17:08
yup I think it was, I've added `init.R` to install them during the build stage.

**Comment by cadecairos** [comment] 2018-04-25 18:35
@vojtechsedlak Can you confirm the version of R that's running on yourshinyapps.io test app?

**Comment by cadecairos** [comment] 2018-04-25 19:46
Currently doing battle with a problem compiling a dependency in the build...

**Comment by vojtechsedlak** [comment] 2018-04-25 19:48
oh sorry, what's the problematic package?

**Comment by cadecairos** [comment] 2018-04-25 20:30
it's xml2, during the Heroku build phase it fails to compile because it can't find a dependency. I confirmed it's installed on build images, I'm trying to pass in custom build flags to point it in the right direction.

**Comment by vojtechsedlak** [comment] 2018-04-26 15:39
Hey @cadecairos, any luck with resolving the issue? We've now pushed the email launch to Saturday, which gives us a bit more time. Thanks again for your help with this.

**Comment by cadecairos** [comment] 2018-05-02 15:44
This has pivoted to a JS application. Will get it ready for launch before Friday.

**Comment by cadecairos** [comment] 2018-05-16 15:09
@vojtechsedlak @alanmoo ping?

**Comment by alanmoo** [comment] 2018-05-16 15:17
Is this the kind of thing that could technically run as a page on the Foundation site with a little work? Or does it need to be on a Node server?

**Comment by vojtechsedlak** [comment] 2018-05-16 16:31
Sorry for the delay. It would be great if we could keep the tool up at least for the rest of the year, as we may keep referencing it in various communications. It doesn't really matter where or how it is hosted, so whatever you think is the best, most feasible option. It certainly does not require a node server.

**Comment by cadecairos** [comment] 2018-05-16 19:38
@alanmoo is it feasible to get this on the foundation site as a single static page? Then we can redirect fbsurvey.mozillafoundation.org there.

**Comment by alanmoo** [comment] 2018-05-16 20:37
Should be. @Pomax Any thoughts on this when you have a chance?

**Comment by cadecairos** [comment] 2018-05-17 17:27
@Pomax it's the assets contained in this directory: https://github.com/mozilla/d3survey/tree/master/src

**Comment by Pomax** [comment] 2018-05-17 19:28
Do we want to treat it like a package, with a step in `npm run build` that runs _its_ build and then copies over the index.html, or is it sufficient to copy over the content of the `dist` dir?

**Comment by Pomax** [comment] 2018-05-17 21:12
It looks like the version of D3 that is used has code that relies on `new Function()`, which in the same category as `eval()` when it comes to CSP disallow rules. As is, we'd either have to allow eval() on the foundation website (which I would strongly advise against), or we may need to run this on a domain where eval() (in its various forms) can't do any harm...

**Comment by Pomax** [comment] 2018-05-17 21:19
Also having a quick look at the index.html code, this line is incredibly dangerous: ` <script>window.jQuery || document.write('<script src="js/vendor/jquery.min.js"><\/script>')</script>` and should just load jquery without checking if it already exists; jquery has built in clobber-protection, whereas document.write is a super dangerous API function that's left over from the very early days of JS when messing with the document bytestream _as the browser was parsing it_ was a good idea =)

**Comment by Pomax** [comment] 2018-05-18 14:51
@cadecairos @alanmoo, any thoughts?

**Comment by alanmoo** [comment] 2018-05-18 15:04
While this should be figured out, I'm fine leaving this where it is for a little while, as we've got more pressing things to work on.

**Comment by cadecairos** [comment] 2018-08-15 15:32
@alanmoo _poke_

**Comment by alanmoo** [comment] 2018-08-22 19:16
Hi, yes, what?

Do we need a static page for this, committed to the repo in a separate Django app? And then we hard-code the project url in a `urls.py` file?

**Comment by cadecairos** [comment] 2018-09-04 13:54
Something like that, I think. The real trouble seems to be the use of very unsave coding practices that we probably don't want on our domain.

**Comment by Pomax** [comment] 2018-09-04 22:31
Do we... still need this tool?

**Comment by cadecairos** [comment] 2018-09-12 15:55
good question, @alanmoo is anyone depending on this being published long-term?

**Comment by alanmoo** [comment] 2018-09-25 13:51
I got the OK from @caltrider in Slack to archive the repo. Filling a follow-up ticket for cleanup

**Closed by alanmoo** 2018-09-25 13:51 UTC
