### ISSUE TITLE
Discuss migration of discourse to Mozilla instance

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#529] opened 2017-08-03 17:43 UTC
To reduce overhead and increase the odds that users will stumble across channels and make new connections, it might make sense to move our communities over to MoCo's discourse instance. 

Questions: 
 - what channels of ours are active and useful?
 - is it possible to migrate users and past conversations?
 - other questions worth asking...?

I talked with Claw about this earlier in the spring and he seemed supportive of the idea. 

https://discourse.mozilla.org/
https://forum.learning.mozilla.org/

cc @cadecairos @alanmoo @jessevondoom

**Comment by cadecairos** [comment] 2017-08-03 17:51
There is also https://forum.mozillascience.org/

**Comment by alanmoo** [comment] 2017-08-03 18:48
cc @hmitsch

**Comment by hmitsch** [comment] 2017-08-03 20:52
cc @LeoMcA @flamingspaz

Please confirm that you see this bug as we are crossing Github orgs here ...

-Henrik

**Comment by xmatthewx** [comment] 2017-08-03 21:00
cc @hannahkane

**Comment by LeoMcA** [comment] 2017-08-04 15:01
> is it possible to migrate users and past conversations?

Yes, it's possible, but whether it's something worth doing is another question.

Last time we did a forum migration, with the add-ons forum, we decided against migrating users and past conversations. As I remember it, this was because technically a migration from phpBB -> Discourse would have been very difficult, and there wasn't a strong desire to keep the old content.

This would be a Discourse -> Discourse migration, so technically a lot easier - and while still some work, I think it'd be worth it.

So some further questions:

- Is there a need to migrate past conversations or do we want to start afresh?

- Is there a need to set up url redirects for posts on the old instances to posts on discourse.mozilla.org
  - I have an idea for how we could make this work

- Aside from mozillians.org, is there anywhere mofo-specific which associates multiple email addresses with the same user
  - This is so we avoid creating duplicate accounts in discourse.mozilla.org

**Comment by xmatthewx** [comment] 2017-08-04 19:10
> Is there a need to migrate past conversations or do we want to start afresh?

I bet a couple of channels are active and would want to bring their history. It's probably also a chance to prune inactive clutter. Does Discourse have a concept of archived channels?

> is there anywhere mofo-specific which associates multiple email addresses with the same user

We're on the Mozilla-wide Salesforce. It could help avoid some dupes, but beyond that, I'm not sure there's a low-labor fix.

**Comment by LeoMcA** [comment] 2017-08-07 20:00
> Does Discourse have a concept of archived channels?

It's not a one button fix, but we move categories to be under our [archives category](https://discourse.mozilla.org/c/archives), make them read only, and set up redirects.

**Comment by alanmoo** [comment] 2017-08-09 19:00
That sounds like a reasonable plan, @LeoMcA.

**Comment by alanmoo** [comment] 2017-08-11 15:08
I'm currently tracking down the stakeholders for 

https://forum.mozillascience.org
https://discourse.mozilla-advocacy.org
https://forum.learning.mozilla.org

and asking them the following:

1. What content can we archive?
2. What categories can we map to MoCo’s instance? (Should they all be consolidated into one parent or do we need to shuffle things a bit?)
3. Do we migrate existing users and content? If it’s just content, I think that’s something that would go into an archive, which we than need to decide on redirects
4. Should we set up URL redirects? (Archived and continually active content)

I'll report back when I have more information.

**Comment by hmitsch** [comment] 2017-08-17 09:03
Hi Alan,

any updates on this?

Regards,
  Henrik

> --
Henrik Mitsch
Senior Manager Participation Systems

irc: hmitsch | skype: henrik.mitsch
Cell: +49 176 99351302

**Comment by alanmoo** [comment] 2017-08-17 20:53
It looks like @amirad and Julia (github name?) are the stakeholders for the learning instance. I sent the above questions and got the following response

>Does this mean we are going to closing the learning.moz discourse group? There are many threads (chad and others have sections on there) and we manage the clubs sections.
>
>Our guess is that it can go into the moco instance. And migrate both content and users. Do we need to change our content or titles at all? Do we send an email to all the users? Is there an opt-in process for people to migrate their info over? And yes to redirects.

@amirad, My understanding is that we would be closing that instance but redirecting users who go there to the sub-group on the MoCo instance. As for the rest, I'm not quite sure how the migration is actually handled. @hmitsch or @LeoMcA maybe you can answer.

As for Science and Advocacy, I'm waiting to hear back but those instances seem nearly abandoned, so if I had to guess, there'll be less to do on that front.

**Comment by xmatthewx** [comment] 2017-08-17 20:59
@amirad – ideally for users, the URL changes, but otherwise the conversation can continue unchanged. As far as communicating the change, can we do it within the discourse channels rather than a bcc email blast?

**Comment by amirad** [comment] 2017-08-17 21:03
@jvallera = julia

@xmatthewx so no changes in sign-on either then?

**Comment by xmatthewx** [comment] 2017-08-17 21:16
@amirad – Sorry. To clarify... I can't speak to what's possible, just to what we should aim to achieve.

**Comment by alanmoo** [comment] 2017-08-21 20:35
Confirmed that https://forum.mozillascience.org/ was abandoned and we can archive the content, as long as existing threads (post spam-reduction) will still be read-only via redirect from their existing links.

**Comment by LeoMcA** [comment] 2017-08-22 14:24
> I can't speak to what's possible, just to what we should aim to achieve.

[**ANYTHING'S POSSIBLLLLLLLLLLLE**](https://www.youtube.com/watch?v=Wcz_kDCBTBk)

Apart from things I've commented on below, I haven't read anything proposed or asked for so far which isn't possible.

*@alanmoo commented:*
>> Is there an opt-in process for people to migrate their info over?
>
> I'm not quite sure how the migration is actually handled.

My plan didn't involve any user interaction - we'd take a database dump of an instance to be migrated, parse it, and import it into discourse.mozilla.org.

Requiring users to opt-in would, make things very complicated. Do we need them to?

I can't answer that question, but to provide some possibly relevant information: discourse.mozilla.org and all the instances potentially migrating share the same [Mozilla TOU](https://www.mozilla.org/en-US/about/legal/terms/mozilla/) and [Privacy Policy](https://www.mozilla.org/en-US/privacy/), aside from forum.learning.mozilla.org which links to the [Webmaker TOU](https://beta.webmaker.org/#/legal).

*@xmatthewx commented:*
> @amirad – ideally for users, the URL changes, but otherwise the conversation can continue unchanged.

The only thing users will have to do is re-authenticate.

*@amirad commented:*
> so no changes in sign-on either then?

Users will continue to be able to authenticate with the same email their old account was registered with.

We use Mozilla's IAM Project for our authentication needs. Today users get these options to authenticate:

* Github
* Google
* Passwordless
* LDAP

The authentication options available on the instances we're potentially migrating are:

* Github
* Webmaker ID
* Persona

Github is already offered, and Persona is dead. If we want to continue offering Webmaker ID, we can look at adding it as an authentication option in IAM.

**Comment by alanmoo** [comment] 2017-08-22 14:47
I don't believe we want to continue offering Webmaker ID. In that case, what happens for a user who previously used it for authentication when we move them over?

**Comment by LeoMcA** [comment] 2017-08-22 14:50
They'll just need to authenticate with another option which proves they own the email address which was associated with their Webmaker ID. Github/Google will likely work for most users, and passwordless will work for all.

**Comment by alanmoo** [comment] 2017-08-23 21:33
Great.

Advocacy feedback:

>We haven't been maintaining or actively engaging the community via our Discourse instance for a while. I would be good to migrate what we can over to the consolidated instance, but minimal effort is fine.
>
>1. Only the Policy + Advocacy Issues category is still relevant; can we archive/keep access to this?
>2. The only relevant category is Policy + Advocacy; everything else can be deleted/hidden (in fact, we should delete/hide them to avoid confusion).
>3. Yes, if possible. Again, only one category is relevant. Over time, we might add one more ("community" or "engage") but we don't have plans to do that right now.
>4. No, there's not enough relevant content for this to be necessary. If we can keep the one category, we'll be fine.

**Comment by LeoMcA** [comment] 2017-09-06 08:37
Looks like we have a 👍 for advocacy and science, and I have enough information to get started writing a migration script. There are still a few questions it'd be great to answer, though: 

**Outstanding learning questions:**

* Do we want to migrate this now, or wait to see how the science/advocacy migration goes and revisit after that?

**Outstanding science/advocacy questions:**

* For science does 'everything' include migrating private topics/messages?
* If no, and since we'll be deleting non-"Policy + Advocacy Issues" content on advocacy, do we want to email users a CSV of their posts before we delete them?
* Considering their inactivity, should we notify users of the migration? Would that be actively (such as an email) or passively (such as a notice for visitors to the site)?

**Comment by xmatthewx** [comment] 2017-09-06 15:32
> or wait to see how the science/advocacy migration goes and revisit after that?

Seems like a good idea to tackle those two first, and then loop back for the more active Learning forum. 

I'll let @alanmoo comment on other outstanding questions.

**Comment by alanmoo** [comment] 2017-09-08 20:13
> For science does 'everything' include migrating private topics/messages?
No
> If no, and since we'll be deleting non-"Policy + Advocacy Issues" content on advocacy, do we want to email users a CSV of their posts before we delete them?
Nope
> Considering their inactivity, should we notify users of the migration? Would that be actively (such as an email) or passively (such as a notice for visitors to the site)?
No, if we set up a redirect to the new board that should be fine.

**Comment by alanmoo** [comment] 2017-09-19 15:47
Got a question from @Melechuga, owner of the Advocacy instance.

>Just wondering how this is going.
Is it possible to change the category title to "Open Policy + Advocacy"? Also, can I be an admin for this category, or is that not the way it would work since we're all under a main mozilla discourse?

**Comment by LeoMcA** [comment] 2017-09-19 16:14
> Just wondering how this is going.

I haven't started writing the migration script yet, but hope to get to it in the next couple of weeks. 

> Is it possible to change the category title to "Open Policy + Advocacy"?

Absolutely!

> can I be an admin for this category, or is that not the way it would work since we're all under a main mozilla discourse?

We don't have any concept of category-level admin/moderation, but we can make @Melechuga a site-wide moderator, which should give her all the permissions necessary to moderate the category.

**Comment by Melechuga** [comment] 2017-10-16 18:55
Hi there,
Given that the migration might still take a while, is it possible to spin up the Open Policy + Advocacy category, and then migrate stuff in? We have a large, new community of interested folks on stand-by, who I'd love to point at discourse asap. Thanks!

**Comment by irvin** [comment] 2017-10-17 04:29
+1 for open a category first and migration old post latter. 
Many things happened each month regards policy that eager to share and discuss with you all.

**Comment by LeoMcA** [comment] 2017-10-18 17:10
@Melechuga it's done! https://discourse.mozilla.org/c/advocacy

I've made you owner of the [about topic](https://discourse.mozilla.org/t/about-the-open-policy-advocacy-category/20610/1) which it'd be great if you could edit to help Discourse users understand what the category is for.

Getting email-in set up is being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1409811

**Comment by Melechuga** [comment] 2017-10-18 19:17
Thanks @LeoMcA!

**Comment by amirad** [comment] 2017-11-07 19:54
Hey all - do we have a timeline for when this stuff will be migrated? cc: @ldecoursy

**Comment by patjouk** [comment] 2017-11-23 16:21
Hey there :) @LeoMcA do you think you can take care of migrating the old data or who do you think should do it?

CC @amirad

**Comment by LeoMcA** [comment] 2017-11-24 14:43
Apologies, we're spread pretty thin on the Discourse front currently.

I'll take care of migrating the old data once I've written the migration script - but this will take a couple of months, maybe more.

If, like with [Open Policy and Adovcacy](https://discourse.mozilla.org/c/advocacy), you want a new category on discourse.mozilla.org now, without migrating old posts (we can always do it later), then that's also possible. :)

**Comment by alanmoo** [comment] 2018-06-26 17:58
@LeoMcA I wanted to check in on this, as it's been a while. I was having a conversation with someone (@cadecairos?) at all hands and I believe we discussed simply backing up and taking down the existing MoFo discourse forums, since they've languished so much, and redirect the urls to the new ones. We can hold onto the data for a bit in case anyone cries out, (though I don't expect them to) and manually pull out data if necessary.

Thoughts?

**Comment by LeoMcA** [comment] 2018-07-10 13:54
Yes, there's no need to keep the existing instances running to migrate them, so they can be taken down, provided we have database backups.

Setting up the new categories is a very simple job, it's migrating the old content which would be at least a few days of work (a few days I haven't found yet).

**Comment by alanmoo** [comment] 2018-07-10 17:59
Cool. @cadecairos Is that stuff you can take care of in the next few weeks?

**Comment by LeoMcA** [comment] 2018-07-11 09:51
Do we have a list of categories I should be setting up, and owners I should be associating with them?

**Comment by alanmoo** [comment] 2018-08-10 15:44
I don't have anyone specifically jumping to get new categories open. I'm wondering if we should really even bother with migrations at this point as it seems there isn't a specific community looking to use this. And unlike brick and mortar businesses, with situations like this the phrase "If you build it, they will come" seems to refer to spammers more than anything else.

Any objections to just redirecting the existing urls to the main discourse.mozilla.org instance and letting people find where to go from the existing categories?

**Comment by cadecairos** [comment] 2018-08-10 15:49
No objections here.

**Comment by acabunoc** [comment] 2018-08-13 16:53
For the mozillascience instance -- I know we were waiting to spin that down till we had a way to migrate all the existing content somewhere discoverable. Not being actively used now. 

cc @stephwright

**Comment by LeoMcA** [comment] 2018-08-15 12:02
I propose the best way to approach this is to:

* Take a database backup for each of the sites
  * This means we can import posts later into discourse.mozilla.org, if absolutely necessary
  * Can be done from `/admin/backups`
* Use a site crawler (like httrack) to create a static HTML archive of the site we can throw up somewhere
  * Possibly even under the existing URLs, provided we add a link to discourse.mozilla.org
* Shut down the instances

**Comment by alanmoo** [comment] 2018-08-15 14:55
What about ripping out a fair amount of the spam that's collected? I assume that would be best to do while it's still running?

**Comment by cadecairos** [comment] 2018-08-15 15:39
This all sounds pretty straight-forward. @patjouk and I will work on this together.

**Comment by cadecairos** [comment] 2018-08-17 15:51
We've enabled Read only, and dumped the database backup into an encrypted S3 bucket, with the git commit SHA noted in the archive.

I'll be shutting down the instance when I get back from vacation in two weeks and have time to put a redirect in place to discourse.mozilla.org

**Comment by patjouk** [comment] 2018-12-21 16:49
Migration is happening for sciences and advocacy instances. For learning, we will wait after the new year, when everyone is back from holidays.

**Comment by cadecairos** [comment] 2019-01-30 16:21
These domain are all now redirecting to discourse.mozilla.org, and the instances have been terminated. Databases have been snapshotted, if we ever need to pull out anything, however, they must be deleted in accordance with our lean data practices policy within the next 6 months.

Please open a new issue to recover any data from one of these instances.

**Closed by cadecairos** 2019-01-30 16:21 UTC
Labels: data-migration, needs discussion

**Comment by xmatthewx** [comment] 2019-01-30 17:32
Amazing. That's a big victory.
